### ISSUE TITLE
IPC Design

### ISSUE THREAD

**Issue by lachlansneff** [nebulet/nebulet#14]
Here's the initial design for IPC (Inter-Procedural Communication):

IPC will exist in two separate stages:
1. Single-Copy
    - Copies data from one module to another.
    - This can be implemented immediately following the creation of a process model.
2. Zero-Copy
    - Moves data between modules without copying data.
    - This allows for the highest-possible throughput.
    - Can only be implemented after WebAssembly has access to a [garbage collector](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md) or [reference-types](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md).

Once zero-copy ipc becomes possible to implement, single-copy ipc will be removed from nebulet unless there is a good reason to keep it.

Comments and discussion are welcome!

**Comment by elszben** [comment]
I assume that each wasm module can have its own heap management (whatever its writer came up with). It means that each module has its own heap. I don't think you can implement zero copy message passing in such a system. The best you can do is that you define shared heaps and copy data there and move ownership somehow. I don't see what this has to do with GC. Care to elaborate?

By the way, I love this topic. I worked on a commercial OS for a while and used to dream about reimplementing singularity in my free time.:)

**Comment by lachlansneff** [comment]
@elszben Thanks for commenting!

Yeah, each module manages it's own heap (although I'll link all running modules against a library that contains a `malloc`/`free`/etc implementation, if they want to use it to decrease binary size.

Basically, while the wasm MVP (minimum viable product) doesn't contain a baked-in gc, in the near future, applications will be able to use a system-supplied garbage collector. Important to note, the gc items will be stored outside of the wasm linear memory. Thus, they will be able to be passed between modules and processes. I plan to build on top of that.

EDIT: Don't forget to join https://gitter.im/nebulet/nebulet

**Comment by losfair** [comment]
@lachlansneff 

For the zero-copy approach, I think a more practical way is to instead provide a handle/buffer/sth. that applications can write (somehow) serialized data into, since it is nearly impossible to rewrite containers in every language targeting wasm to inform the OS of the heap layout (which should be an implementation detail).

Environment-provided garbage collectors won't help much, as wasm is designed to be suitable for very low-level code (which is often the case for C/C++/Rust), where there isn't a concept of object and everything is raw bytes in the linear memory.

**Comment by lachlansneff** [comment]
Well, for now, at least, it'll just be single copy. I do also want to have a more flexible, but slower method of ipc for instances where performance isn't as important.

1. Have an abi method that you use to declare a writable buffer of some size. Then, you wait in an event loop and another process can tell the os to copy write from them to that buffer, and then the process will be notified.
2. Copy from a process into a kernel buffer and then copy from that buffer into a process. More flexible, but slower.

**Comment by chpio** [comment]
> If a process could mark part of its linear memory as a "swap-ipc region", another process, having received a handle from said process could "flip" part of its own memory into that swap space. This would be fast and would avoid fragmenting the wasm linear memory with periodic unmapped pages.

https://github.com/lachlansneff/lachlansneff.github.io/issues/2#issuecomment-393002128

**Comment by chpio** [comment]
@lachlansneff you mentioned "flipping" the shared memory, i guess it's done by paging that memory? This should also be implementable in software (if you target eg a minimalistic RISC-V without an MMU), i guess? What do you think is the performance cost for that?
