### ISSUE TITLE
Implement a Preemptive Scheduler

### ISSUE THREAD

**Issue by lachlansneff** [nebulet/nebulet#2]
The building blocks are there.

### What needs to be done

- [x] Implement a `Thread` type.

- [x] Decide whether to go for Thread IDs or not.

- [x] Get thread context switching working.

**Comment by ghost** [comment]
Since nebulet doesn't have the the overhead of context switching, the disadvantages of native threads don't apply. Or perhaps any implementation of threads on a ring 0 OS is green (?).

Green threads summarized by the world view of Erlang (taken from [wikipedia.org/wiki/Erlang](https://en.wikipedia.org/wiki/Erlang_(programming_language)))

 - Everything is a process.
 - Processes are strongly isolated.
 - Process creation and destruction is a lightweight operation.
 - Message passing is the only way for processes to interact.
 - Processes have unique names.
 - If you know the name of a process you can send it a message.
 - Processes share no resources.
 - Error handling is non-local.
 - Processes do what they are supposed to do or fail.

By this specification Thread IDs would be implemented as unique process names (possibly unsigned integers or hashes).

**Comment by lachlansneff** [comment]
Most of those attributes sound excellent.

We do have to be careful, however: While wasm doesn't currently have threading support, it will eventually, and I'd like to support that.

So, I think we do need some separation between processes and threads (e.g. A process has a list of threads.)

Also, I've already taken a little from Fuchsia's book and I really like their concept of handles. Specifically, to do anything, you need a handle. For example, to kill a process, you'd need its handle.

Lastly, since it'll be a microkernel, I was thinking that just "servers" would have names.

These are just off the top of my head. Correctly if there's better ways of doing anything!

**Comment by Ericson2314** [comment]
https://github.com/nathan7/libfringe can work anywhere

**Comment by lachlansneff** [comment]
@Ericson2314 Does libfringe support preemptive context switching?

EDIT: I looked at the libfringe docs. Unfortunately, it won't fit this use case, but we can most likely borrow code/ideas from it.

**Comment by Ericson2314** [comment]
Ah *preemptive* scheduling; missed that. When do you turn the WASM into native code? If the kernel does this, it can sprinkle optional coopertive yields everywhere such that the same  guarantees as timer/interrupt-based preemptive scheduling are met.

**Comment by lachlansneff** [comment]
That would work, but it'd have a lot of overhead. The interrupt timer already works, it should use that. I did have a preemptive scheduler almost working, but it was pretty badly designed, so I got rid of it and focused on getting wasm executing.

**Comment by ghost** [comment]
While I agree that a pure ring-0 OS would mean that IPC / message-passing would be very low-overhead and process spawning very fast (effectively turning processes into "green threads"), I disagree that this should obsolete shared memory.

I think shared memory is still a useful paradigm to support and an OS should not be restricting the programming paradigms that applications can use. There should be a concept of memory sharing (although it will be used far less when IPC is low-overhead).

I think the right distinction between "processes" and "threads" should be with regards to what memory is visible/accessible to them. This is similar to our current OSs, where all threads of a process share the same address space. In Nebulet, it would mean that spawning a thread and spawning a process are almost the same operation, but the former preserves all the memory allocations and shares them with its parent, while the latter does not.

This definitely needs more thought, though.

**Comment by lachlansneff** [comment]
Wasm doesn't actually support threads right now, so processes don't *need* to support multiple threads just yet, but the design should obviously allow for it.

IPC is more difficult than it seems in wasm, as well, since it will most likely still have to copy memory between SIPs. It would be no-copy ideally, but there's no concept of shared memory regions in wasm (aside from multiple linear memories, which isn't in the spec yet), so there is no way to share memory without direct memory mapping.

**Comment by lachlansneff** [comment]
This appears to be completed!
