### ISSUE TITLE
Add a random function to the ABI

### ISSUE THREAD

**Issue by g2p** [nebulet/nebulet#29]
(I'm trying to figure out a good first issue to expand the ABIs)

Entropy is a complicated issue for operating systems, but there's the simpler approach of exposing something based on the rdrand instructions.

**Comment by gmorenz** [comment]
This seems like a reasonable way to jump in to me.

**Comment by lachlansneff** [comment]
I agree! Eventually, I'd actually like to supply randomness to SIPs by having them talk to a server process over ipc that supplies random data, but for starting up, this works just fine!

**Comment by g2p** [comment]
I like the server process idea, because process startup gives a good place for initialisation and figuring out if the instruction is supported (and for configurable sources, later on).
But this raises a few questions. How does the server process register itself? How does it get notified that there's an IPC call? The IPC ABI is currently only sketched out I think?

**Comment by g2p** [comment]
I've pushed a patch to add a simple ABI. Comments?
