### ISSUE TITLE
Expand Tools

### ISSUE THREAD

**Issue by lachlansneff** [nebulet/nebulet#3]
The `cargo boot` command is rather minimal and requires editing the source code to change between debug and release mode.

- [ ] Add the ability to supply build type.

- [ ] Select whether to wait for gdb to connect by a process argument.

**Comment by ghost** [comment]
I was looking earlier today into using [`cargo-make`](https://crates.io/crates/cargo-make) for my own project (instead of `Make`). I'll look into it and make a pr if it's good for those purposes

**Comment by lachlansneff** [comment]
@pi-pi3 If possible, I'd rather expand the current build system. If that's too restrictive, I'm happy to move to `cargo make`.

**Comment by jdanford** [comment]
I'd be happy to work on this!

**Comment by lachlansneff** [comment]
Fantastic! The features which are needed are being able to specify `debug` (the default) or `release` and supplying the command line arguments to qemu to pause until a debugger attaches (and maybe autolaunch rustgdb?).

**Comment by jinankjain** [comment]
First part is kind of done automatically by bootimage

For running nebulet in release mode

`bootimage build --release`
`bootimage run --release`

**Comment by lachlansneff** [comment]
Yeah, this issue is from before the bootimage tool existed.
