### ISSUE TITLE
Move the kernel to a submodule.

### ISSUE THREAD

**Issue by lachlansneff** [nebulet/nebulet#33]
The kernel itself should be moved to a submodule, much like [nebulet/abi](https://github.com/nebulet/abi).

**Comment by gmorenz** [comment]
On a only somewhat related note, what is the distinction between things that live in `lib/crate` and things that live in `/crate`?

**Comment by lachlansneff** [comment]
There's not really a distinction. I'm happy to rearrange them, if it'd make more sense to put them all in the same place.
