### ISSUE TITLE
Creating disk image failure

### ISSUE THREAD

**Issue by boneyard93501** [nebulet/nebulet#40]
``` bash
os x 10.11.6
rustc 1.28.0-nightly (990d8aa74 2018-05-25)
cargo 1.28.0-nightly (f352115d5 2018-05-15)
```
getting tripped up at the last step ... so close :)
```bash
93501@mbp15 ~/localdev/source-code/forks/nebulet (master) $ bootimage run
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
    Updating registry `https://github.com/rust-lang/crates.io-index`
Creating disk image at bootimage.bin
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
93501@mbp15 ~/localdev/source-code/forks/nebulet (master) $ ll
total 45376
-rw-r--r--   1 93501  staff   419B May 31 00:36 x86_64-nebulet.json
<snip>
drwxr-xr-x  28 93501  staff   952B May 31 00:37 cretonne/
drwxr-xr-x   6 93501  staff   204B May 31 00:40 target/
-rw-r--r--   1 93501  staff    22M May 31 00:42 bootimage.bin
```

**Comment by lachlansneff** [comment]
This is probably where the error is: https://github.com/rust-osdev/bootimage/blob/ca60ccb940d81efac4e25a5be1d1e1aad7635249/src/build.rs#L343

I'm not sure how though. Maybe it's trying to query the metadata and the built kernel got deleted somehow before that?

**Comment by phil-opp** [comment]
I just published a new version of bootimage with better error messages.

I suspect that your problem is that QEMU isn't installed.

**Comment by boneyard93501** [comment]
@phil-opp  thanks for the update. after pulling the update, all is well. Hello from wasm! :)   many thanks.
