### ISSUE TITLE
make nebulet an exokernel

### ISSUE THREAD

**Issue by unmellow** [nebulet/nebulet#68]
one thing I'm thinking is wouldn't it be a better idea to make an exokernel and have the wasm VM be a library os kinda like ExOS https://github.com/gwoplock/ExOS/issues

**Comment by unmellow** [comment]
even if you do that still means that the kernel is going to be quite large
at least in comparison to an exokernel and as we all know 
big kernels are bad because they're more likely to crash 
and if they crash you have to restart the whole computer also 
sense the VM would be a library instead of the kernel itself 
you could implement some of the more advanced wasm features 
like a garbage collector or a dom, which would allow programs in general
to be smaller now I know wasm doesn't (currently) support either of those
but it will and having those in the kernel itself would make your kernel 
huge maybe even the size of a monolith like Linux which again would be bad

edit I don't mean to sound rude if I do sound rude it's because I can't make a 
good sentence to save my life also I'm not an os dev just a computer lover so 
take everything I said with a grain of salt

**Comment by unmellow** [comment]
when I initially made this issue I had no idea what I was talking about
so here's a new idea instead of having nebulet run on an exokernel have it be an exokernel
I know you can optimize the heck out of system calls since there now just function calls
but you could also have a library running on nebulet to add that functionality

**Comment by lachlansneff** [comment]
What is the difference between nebulet being an exokernel and nebulet being a monolithic kernel?

**Comment by unmellow** [comment]
one potential use case for nebulet is as a base kernel that runs under more specialized oses all it would be in this case is a VM that runs on any given machine

**Comment by unmellow** [comment]
yeah 

edit: rereading my post here I sound very rude I both should have done more research before opening this issue and I should have been more polite in the wording of my comments
