### ISSUE TITLE
Why not part of the linux kernel? Just out of interest

### ISSUE THREAD

**Issue by maxwell-clarke-intranel** [nebulet/nebulet#69]
Would it be possible to implement a ring-0 wasm VM as a linux kernel module? I can see this being easier to integrate with existing systems, and thus have faster uptake than a completely new kernel.

**Comment by levex** [comment]
https://github.com/cervus-v/cervus

**Comment by lachlansneff** [comment]
As @levex noted above, this has already been tried. The project seems to be dead at the moment, however.

**Comment by maxwell-clarke-intranel** [comment]
Thanks!
